### ISSUE TITLE
Error: Cannot read property 'labels' of undefined

### ISSUE THREAD

**Issue by anmlnath** [dangoslen/changelog-enforcer#140]
**Describe the bug**

Changelog enforcer is unable to run on pushes to main, but it still tries.

**To Reproduce**

If I want the other steps in my job to still run if somebody pushes to main, I might put something like this:

```yaml
name: Pull Request Workflow
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  push:
    branches:
      - main
```

Unfortunately changelog-enforcer fails with the error:

`Error: Cannot read property 'labels' of undefined`

**Expected behavior**

Likely fail because the CHANGELOG.md hasn't changed.

**Workaround**

Making changelog-enforcer conditional works around the issue:

```yaml
- if: ${{ github.event_name == 'pull_request' }}
  uses: dangoslen/changelog-enforcer@v2
  with:
    changeLogPath: 'CHANGELOG.md'
    skipLabels: 'no changelog'
```
