### ISSUE TITLE
Warning in Changelog Enforcer output

### ISSUE THREAD

**Issue by mathomp4** [dangoslen/changelog-enforcer#222]
**Describe the bug**

I recently tried adding the Changelog Enforcer to a repo and was doing the usual "Will it fail without a changelog change?" test and in the action output I saw:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Thought I'd let you know.

**To Reproduce**

I think this should happen all the time as it's GitHub itself issuing the warning.

**Expected behavior**

I suppose no warning? 😄 

**A link to or sample of your workflow**

```yaml
name: "Enforce Changelog"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: 'ChangeLog.md'
        skipLabels: 'skip changelog'
        missingUpdateErrorMessage: >
            No update to ChangeLog.md found! Please add a changelog
            entry to it describing your change.  Please note that the
            keepachangelog (https://keepachangelog.com) format is
            used. If your change is very trivial not applicable for a
            changelog entry, add a 'Skip Changelog' label to the pull
            request to skip the changelog enforcer.
```

**Comment by dangoslen** [comment]
Thanks, @mathomp4 

I'm aware and just haven't had the chance to go back through each workflow. But I'll try to get through it today.

**Comment by mathomp4** [comment]
> Thanks, @mathomp4
> 
> I'm aware and just haven't had the chance to go back through each workflow. But I'll try to get through it today.

@dangoslen I figured you were and frankly I only noticed it because I was checking to see if the Error Message looked right to me. Usually the enforcer does its job and I never look at the Actions output

Thanks for the great tool!

**Comment by dangoslen** [comment]
I think this is resolved now as I've removed all `set-output` commands in the workflows

**Comment by tdilauro** [comment]
I am still seeing this warning with v3.3.0...

```
Run dangoslen/changelog-enforcer@v3.3.0
  with:
    changeLogPath: CHANGELOG.md
    skipLabels: no-changelog
    versionPattern: ^## \[((v|V)?\d*\.\d*\.\d*-?\w*|unreleased|Unreleased|UNRELEASED)\]
    token: ***
Skip Labels: no-changelog
Changelog Path: CHANGELOG.md
Missing Update Error Message: No update to CHANGELOG.md found!
Expected Latest Version: 
Version Pattern: ^## \[((v|V)?\d*\.\d*\.\d*-?\w*|unreleased|Unreleased|UNRELEASED)\]

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: No update to CHANGELOG.md found!
```

Here is an example of the workflow...
```
name: CI

on:
  # will run on all PRs that are opened or updated (synchronized)
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # changelog must be edited for every PR
  changelog:
    name: Updates Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3.3.0
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabels: "no-changelog"
```
