### ISSUE TITLE
new skipLabels option doesn't work with labels with spaces

### ISSUE THREAD

**Issue by RAnders00** [dangoslen/changelog-enforcer#58]
**Describe the bug**
I used to have a setting of `skipLabel: 'no changelog entry needed'` in my config file. I cannot upgrade to v1.6.0 because the new version parses a setting of `skipLabels: 'no changelog entry needed'` as `Skip Labels: no,changelog,entry,needed` (as per the job log).

**To Reproduce**
- Create a label "no changelog entry needed"
- Setup a GitHub action like this:
```yaml
name: Changelog Check

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Gives an error if there's no change in the changelog (except using label)
      - name: Changelog check
        uses: dangoslen/changelog-enforcer@v1.6.0
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'no changelog entry needed'
```
- Result: PRs with the "no changelog entry needed" label still don't pass CI.

**Expected behavior**
I thought the new behaviour was to only split on comma, not on spaces too.

**A link to or sample of your workflow**
https://github.com/robotty/simple-process-stats/blob/7ed34ca9718b82e942e4a6483b20fd3a5faa1332/.github/workflows/changelog-check.yml
https://github.com/robotty/simple-process-stats/pull/9
https://github.com/robotty/simple-process-stats/pull/9/checks?check_run_id=1563404236
